# Basic
title: Jim
subtitle: "你的朋友圈好久没有提及你的快乐了，你的梦想、浪漫、晚霞和音乐都没了，怎么了？是不是和我一样进厂了？"
welcome_message: ""
description: Hello, I am Jim.
creator: <a href="http://onev.cat">@onevcat</a>
# 头像里的标题
avatarTitle: Jim
# 头像里的描述
avatarDesc: Studying developer
url: "https://huanghongxing-jim.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页
    # description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'} 

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: huanghongxing-jim
    mail: huanghongxingjim@163.com
    
# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
